// Warning: this file is automatically generated by `npm run update-prefixes` (Font Awesome API release 7.3.1)
export default {
  "prefixes": [
    "fas",
    "far",
    "fal",
    "fat",
    "fab",
    "fad",
    "fadr",
    "fadl",
    "fadt",
    "fass",
    "fasr",
    "fasl",
    "fast",
    "fasds",
    "fasdr",
    "fasdl",
    "fasdt",
    "facr",
    "faes",
    "fagt",
    "fajr",
    "fajdr",
    "fajfr",
    "fams",
    "fans",
    "fands",
    "fapr",
    "faslr",
    "fasldr",
    "faslpr",
    "faslpdr",
    "fatl",
    "fausb",
    "faudsb",
    "faufsb",
    "favs",
    "fawsb"
  ],
  "styles": [
    "solid",
    "regular",
    "light",
    "thin",
    "brands",
    "semibold"
  ],
  "families": [
    "classic",
    "duotone",
    "sharp",
    "sharp-duotone",
    "chisel",
    "etch",
    "graphite",
    "jelly",
    "jelly-duo",
    "jelly-fill",
    "mosaic",
    "notdog",
    "notdog-duo",
    "pixel",
    "slab",
    "slab-duo",
    "slab-press",
    "slab-press-duo",
    "thumbprint",
    "utility",
    "utility-duo",
    "utility-fill",
    "vellum",
    "whiteboard"
  ],
  "familyStyleToPrefixMap": {
    "classic": {
      "solid": "fas",
      "regular": "far",
      "light": "fal",
      "thin": "fat",
      "brands": "fab"
    },
    "duotone": {
      "solid": "fad",
      "regular": "fadr",
      "light": "fadl",
      "thin": "fadt"
    },
    "sharp": {
      "solid": "fass",
      "regular": "fasr",
      "light": "fasl",
      "thin": "fast"
    },
    "sharp-duotone": {
      "solid": "fasds",
      "regular": "fasdr",
      "light": "fasdl",
      "thin": "fasdt"
    },
    "chisel": {
      "regular": "facr"
    },
    "etch": {
      "solid": "faes"
    },
    "graphite": {
      "thin": "fagt"
    },
    "jelly": {
      "regular": "fajr"
    },
    "jelly-duo": {
      "regular": "fajdr"
    },
    "jelly-fill": {
      "regular": "fajfr"
    },
    "mosaic": {
      "solid": "fams"
    },
    "notdog": {
      "solid": "fans"
    },
    "notdog-duo": {
      "solid": "fands"
    },
    "pixel": {
      "regular": "fapr"
    },
    "slab": {
      "regular": "faslr"
    },
    "slab-duo": {
      "regular": "fasldr"
    },
    "slab-press": {
      "regular": "faslpr"
    },
    "slab-press-duo": {
      "regular": "faslpdr"
    },
    "thumbprint": {
      "light": "fatl"
    },
    "utility": {
      "semibold": "fausb"
    },
    "utility-duo": {
      "semibold": "faudsb"
    },
    "utility-fill": {
      "semibold": "faufsb"
    },
    "vellum": {
      "solid": "favs"
    },
    "whiteboard": {
      "semibold": "fawsb"
    }
  },
  "prefixToFamilyStyleMap": {
    "fas": {
      "family": "classic",
      "style": "solid"
    },
    "far": {
      "family": "classic",
      "style": "regular"
    },
    "fal": {
      "family": "classic",
      "style": "light"
    },
    "fat": {
      "family": "classic",
      "style": "thin"
    },
    "fab": {
      "family": "classic",
      "style": "brands"
    },
    "fad": {
      "family": "duotone",
      "style": "solid"
    },
    "fadr": {
      "family": "duotone",
      "style": "regular"
    },
    "fadl": {
      "family": "duotone",
      "style": "light"
    },
    "fadt": {
      "family": "duotone",
      "style": "thin"
    },
    "fass": {
      "family": "sharp",
      "style": "solid"
    },
    "fasr": {
      "family": "sharp",
      "style": "regular"
    },
    "fasl": {
      "family": "sharp",
      "style": "light"
    },
    "fast": {
      "family": "sharp",
      "style": "thin"
    },
    "fasds": {
      "family": "sharp-duotone",
      "style": "solid"
    },
    "fasdr": {
      "family": "sharp-duotone",
      "style": "regular"
    },
    "fasdl": {
      "family": "sharp-duotone",
      "style": "light"
    },
    "fasdt": {
      "family": "sharp-duotone",
      "style": "thin"
    },
    "facr": {
      "family": "chisel",
      "style": "regular"
    },
    "faes": {
      "family": "etch",
      "style": "solid"
    },
    "fagt": {
      "family": "graphite",
      "style": "thin"
    },
    "fajr": {
      "family": "jelly",
      "style": "regular"
    },
    "fajdr": {
      "family": "jelly-duo",
      "style": "regular"
    },
    "fajfr": {
      "family": "jelly-fill",
      "style": "regular"
    },
    "fams": {
      "family": "mosaic",
      "style": "solid"
    },
    "fans": {
      "family": "notdog",
      "style": "solid"
    },
    "fands": {
      "family": "notdog-duo",
      "style": "solid"
    },
    "fapr": {
      "family": "pixel",
      "style": "regular"
    },
    "faslr": {
      "family": "slab",
      "style": "regular"
    },
    "fasldr": {
      "family": "slab-duo",
      "style": "regular"
    },
    "faslpr": {
      "family": "slab-press",
      "style": "regular"
    },
    "faslpdr": {
      "family": "slab-press-duo",
      "style": "regular"
    },
    "fatl": {
      "family": "thumbprint",
      "style": "light"
    },
    "fausb": {
      "family": "utility",
      "style": "semibold"
    },
    "faudsb": {
      "family": "utility-duo",
      "style": "semibold"
    },
    "faufsb": {
      "family": "utility-fill",
      "style": "semibold"
    },
    "favs": {
      "family": "vellum",
      "style": "solid"
    },
    "fawsb": {
      "family": "whiteboard",
      "style": "semibold"
    }
  }
}